# Generated by Django 2.0.9 on 2018-11-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbk', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Cliente',
        ),
    ]
